### ISSUE TITLE
HotSpot not work

### ISSUE THREAD

**Issue by mupm1** [marianmoldovan/panoramagl#117]
on 1.9.1 panorama.addHotspot not work. Arrows are not displayed

**Comment by hannesa2** [comment]
Indeed, with #119 it will work again.
(Sadly the Espresso test hang and doesn't work)

But with mandatory #114 (fix for graphic memory consumption) the click in Emulator doesn't work anymore.
On Pixel 4 it works properly.

Any help is welcome

**Comment by hannesa2** [comment]
When you do 
`git revert 7e938a98bdc3b223`
The click in Emulator will work again, because Emulator use `PLOpenGLVersion1_0` but it found
`OpenGL ES-CM 1.1 (4.1 Metal - 71.7.1)`

No clue why `PLOpenGLVersion1_0` works here.
Btw, with the revert, the memory consumption on real device is very high again

**Comment by mupm1** [comment]
android version getter was wrong. i fixed it. On Samung A70 and Samsung A90 it works properly.

**Comment by hannesa2** [comment]
#120 tried to solve the click in Emulator, but it still not working.
On my Pixel 4 it made no difference

**Comment by mupm1** [comment]
I think if we go back to version 1.8 and just change method getAndroidVersion , everything will be fine.

**Comment by mupm1** [comment]
version 1.8.0 on Android <10 works fine . getAndroidversion method is get wrong on Android =>10. so I think if we go back to version 1.8 and just change method getAndroidVersion , everything will be fine.

**Comment by mupm1** [comment]
version 1.8 and just change method getAndroidVersion -- Android 11
![image](https://user-images.githubusercontent.com/7701890/137621325-e64d6596-cd6b-48f0-a1c2-b92d5192b9ac.png)

**Comment by mupm1** [comment]
and on Emulator hotspots works.

![image](https://user-images.githubusercontent.com/7701890/137621592-3c4e4831-15aa-4835-861a-e323d4e8acd9.png)

**Comment by mupm1** [comment]
whats your idea? @hannesa2

**Comment by hannesa2** [comment]
I've an suspect: the usage of `getAndroidVersion() < 3` 
This is probably wrong, because it doesn't respect `isEmulator()` in `getOpenGLVersion()`

Only usage of `getOpenGLVersion()` is valid

**Comment by Gourav19961996** [comment]
override fun onLongPress(e: MotionEvent) {

        val x = e.x
        val y = e.y
        val screenWidth = resources.displayMetrics.widthPixels
        val screenHeight = resources.displayMetrics.heightPixels
        val normalizedX = x / screenWidth
        val normalizedY = y / screenHeight

        addHotspotAt(normalizedX, normalizedY, screenWidth, screenHeight)
        Toast.makeText(this, "${normalizedX}, ${screenHeight}", Toast.LENGTH_SHORT).show()
    }

    private fun addHotspotAt(
        normalizedX: Float, normalizedY: Float, screenWidth: Int, screenHeight: Int
    ) {
        // These values would ideally come from your panorama viewer or camera settings
        val currentYaw = plManager.panorama.camera.yaw
        val currentPitch = plManager.panorama.camera.pitch
        val fov = plManager.panorama.camera.fov  // Current FOV considering zoom
        val aspectRatio = screenWidth.toFloat() / screenHeight

        // Convert normalized screen coordinates to changes in yaw and pitch
        val yawChange = (normalizedX - 0.5f) * fov
        val pitchChange = (0.5f - normalizedY) * (fov / aspectRatio)

        // Calculate new yaw and pitch for the hotspot
        val hotspotYaw = (currentYaw + yawChange) % 360
        val hotspotPitch = currentPitch + pitchChange
        // Ensure pitch stays within bounds [-90, 90]
        val clampedPitch = hotspotPitch.coerceIn(-90f, 90f)

        // Now, create your hotspot at this new yaw and pitch
        createHotspot(hotspotPitch = clampedPitch, hotspotYaw = hotspotYaw)
    }

    private fun createHotspot(hotspotPitch: Float, hotspotYaw: Float) {
        val hotspot = ActionPLHotspot(
            this,
            System.currentTimeMillis(),
            PLImage(BitmapFactory.decodeResource(resources, R.raw.hotspot)),
            hotspotPitch,
            hotspotYaw,
            PLConstants.kDefaultHotspotSize,
            PLConstants.kDefaultHotspotSize
        )
        plManager.panorama.addHotspot(hotspot)
    }
